### ISSUE TITLE
Conflicting names with sidekiq gem

### ISSUE THREAD

**Issue by Shwetakale** [harvesthq/sidekiq-monitor-stats#6]
This gem is extension of ```sidekiq``` gem. This use ```Sidekiq::Monitor``` as module however sidekiq has class with name ```Sidekiq::Monitor```. When we try to create instance of class defined in sidekiq gem it is conflicting with module added by this gem and we are unable to create instance. 

Error is as follows

````
.rvm/gems/ruby-2.7.0/gems/sidekiq-throttled-0.11.0/lib/sidekiq/throttled/expirable_list.rb:39:in `initialize'
.rvm/gems/ruby-2.7.0/gems/sidekiq-throttled-0.11.0/lib/sidekiq/throttled/fetch.rb:21:in `new'
.rvm/gems/ruby-2.7.0/gems/sidekiq-throttled-0.11.0/lib/sidekiq/throttled/fetch.rb:21:in `initialize'
````

**Comment by mrsimo** [comment]
Thanks for the report @Shwetakale. We haven't upgraded to sidekiq 6 yet, so hadn't gotten this problem yet. Gonna take a look.

**Comment by mrsimo** [comment]
@Shwetakale version 0.0.4 should be available fixing this error. Let me know if something doesn't work!

**Comment by Shwetakale** [comment]
@mrsimo We are using this with Sidekiq 6 and working fine however lets take an example if some one wants to create instance of Sidekiq::Monitor in that case it will create issue. In our case it wont work with sidekiq-throttled gem

**Comment by mrsimo** [comment]
Yeah! Noticed that when trying to trigger the failure. With v0.0.4 things should be fine with sidekiq-throttled or trying to use `Sidekiq::Monitor`.

**Comment by Shwetakale** [comment]
Just saw your commits.  Woo-hoo!  This was very quick. Thank you @mrsimo :)
